[build]
builder = "nixpacks"
buildCommand = "cd backend && mvn clean package -DskipTests"

[deploy]
startCommand = "cd backend && chmod +x start.sh && ./start.sh"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.environmentVariables]
SPRING_PROFILES_ACTIVE = "prod"
