[build]
builder = "nixpacks"
buildCommand = "cd backend && mvn clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -Dserver.port=$PORT -Dspring.profiles.active=prod -jar target/*.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3
