[build]
builder = "nixpacks"
buildCommand = "cd backend && mvn clean package -DskipTests"

[deploy]
startCommand = "cd backend && java -Dserver.port=$PORT -jar target/*.jar"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[deploy.environmentVariables]
SPRING_PROFILES_ACTIVE = "prod"
